{
   "admin_service": "${admin-service}",
   "admin_service_port": "${admin-service-port}",
   "cluster_service": "${cluster-service}",
   "cluster_service_port": "${cluster-service-port}",
   "jenkins_service": "${jenkins-service}",
   "jenkins_service_port": "${jenkins-service-port}",
   "ocir_ingress_image_tag":"${ocir_ingress_image}",
   "ingress_namespace":"${ingress_namespace}",
   "ingress_ocir_secret_name":"${ingress_ocir_secret_name}",
   "ingress_lb_service_name":"${ingress_lb_service_name}",
   "ingress_lb_shape":"${ingress_lb_shape}",
   "ingress_enable_http_port":${ingress_enable_http_port},
   "ingress_enable_https_port":${ingress_enable_https_port},
   "ingress_http_port":"${ingress_http_port}",
   "ingress_https_port":"${ingress_https_port}",
   "jenkins_namespace":"${jenkins_namespace}",
   "wls_domain_namespace":"${wls-domain_namespace}",
   "cert_secret_name": "${cert_secret_name}",
   "lb_name": "${lb_name}",
   "lb_namespace": "${lb_namespace}",
   "lb_shape": "${lb_shape}",
   "is_internal": ${is_internal},
   "service_ssl_port" : "${service_ssl_port}"
 }